platform :ios, '7.0'
pod 'Parse-iOS-SDK', '~> 1.2.16'
pod 'MBProgressHUD', '~> 0.8'
pod 'PBWebViewController', '~> 0.1'
pod 'SDWebImage', '~> 3.5'
pod 'Reachability', '~> 3.1'
pod 'CocoaLumberjack', '~> 1.8'
#pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :commit => '6863ec67fb08d81f4bf1090df1fbaa9e6c945fe5'
pod 'MagicalRecord', '~> 2.2'
pod 'CrashlyticsFramework', '~> 2.1'
#pod 'Reveal-iOS-SDK', '~> 1.0'
