platform :ios, '7.0'
pod 'Parse-iOS-SDK', '~> 1.2.16'
pod 'MBProgressHUD', '~> 0.8'
pod 'MagicalRecord', '~> 2.2'
pod 'PBWebViewController', '~> 0.1'
pod 'SDWebImage', '~> 3.5'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.0'
